### ISSUE TITLE
not correctly sending type string format binary

### ISSUE THREAD

**Issue by thurt** [byu-oit/openapi-enforcer-middleware#14]
I have a controller that uses `res.send(picture)` where `picture` is type `Uint8Array`. In the controller I have set `res.set("Content-Type", "image/jpeg")`. The issue appears to be in this area of openapi-enforcer-middleware's `res.send`

<img width="1335" alt="Screen Shot 2019-05-28 at 3 26 28 AM" src="https://user-images.githubusercontent.com/8955144/58459022-78e48e00-80f8-11e9-88a9-59400569a574.png">

when this body is sent into express their code automatically adds a `utf-8` charset to `Content-Type`. I believe this charset addition is preventing client from displaying the content correctly (shows as broken image). offending express code below:

<img width="724" alt="Screen Shot 2019-05-28 at 3 22 16 AM" src="https://user-images.githubusercontent.com/8955144/58458777-02479080-80f8-11e9-92e2-eb99065330da.png">

If I modify code in openapi-enforcer-middleware to pass the original `body` to express's `res.send` then it works fine, but this is obviously not a viable solution
```js
if (response.hasOwnProperty('body')) {
     const sendObject = response.schema
        ? ['array', 'object'].indexOf(response.schema.type) !== -1 
        : typeof response.body === 'object'
      res.send(body) // modified
}
```

**Comment by thurt** [comment]
The best solution I can think of is to add a custom schema property `x-serialize: false` that openapi-enforcer checks for before trying to serialize the value. that would prevent openapi-enforcer from serializing the `response.body` into a string (because passing a string type to express' `res.send` causes `utf-8` charset to automatically be added).

this would also require a check in openapi-enforcer-middleware so it does not try to construct a string from the body with `String(response.body)`. 

Curious to hear if you have other ideas

**Comment by Gi60s** [comment]
I think you have three solutions that you could use in this case.

**Option 1**

Use the [Open API Enforcer's Schema Value](https://byu-oit.github.io/openapi-enforcer/api/components/schema-value/) to specify that the body should not be serialized. You're code might look something like this afterward:

```js
const Enforcer = require('openapi-enforcer')
const SchemaValue = Enforcer.v3_0.Schema.Value

exports.myController = async function (req, res) {
  res.set('content-type', 'image/jpg')
  const picture = await getPicture()
  const body = new SchemaValue(picture, { serialize: false })
  res.send(body)
}
```

If you go with this option, you'll want to update to `openapi-enforcer@1.3.4` since I tested this to verify it would work and found a bug, which I fixed.

**Option 2**

Create a [custom data type format](https://byu-oit.github.io/openapi-enforcer/api/components/schema#definedatatypeformat) that does not serialize the image. You'd need to come up with a new format name, maybe something like `binary-stream` or `actually-binary`. Then put that format in you Open API document in place of `binary`.

**Option 3**

Bypass the `send` function and instead just use the `res.write` and `res.end` functions, or use `res.pipe`, or use `res.sendFile`. I think all three of these would bypass both validation and serialization.

**Comment by thurt** [comment]
Thanks I was not aware that I could do anything like this! i will try these

**Comment by Gi60s** [comment]
Now that I think about it, the third option mentions `res.pipe` which is incorrect. What you'd actually to is pipe to the response object (not from it). So if you had a read stream then you could pipe it to the response object.

Something like this:

```js
const fs = require('fs')

const readStream = fs.createReadStream('/path/to/file')
readStream.pipe(res)
```
