### ISSUE TITLE
how to make custom response in v2? seems it does not get to error handler

### ISSUE THREAD

**Issue by freerider7777** [byu-oit/openapi-enforcer-middleware#60]
```
  const initOptions = {
    allowOtherQueryParameters: true, // 2
    handleBadRequest: false,
    handleBadResponse: false, // 3
    handleNotFound: true,
    handleMethodNotAllowed: true
  }
```

if there is some OpenAPI error in request it does not get to error catching middleware (next normal middleware is called):

```
  // add error catching middleware
  app.use((err, req, res, next) => {
```

**Comment by freerider7777** [comment]
seems like (utils2.js)
`function handleRequestError(opts, error, res, next) {`
needs 
`next(error);`
instead of 
`next();`

**Comment by Gi60s** [comment]
Sorry on the slow response here. I'll be a little slow on replying throughout this week.

As you've already discovered, by setting the `handleBadRequest` option to `false` you allow it to call the next middleware even if the request had errors. You can tell if the request had errors because the `openapi` property will not be set on the request object.

What isn't helpful here is that you can't easily see what the client error was.

Here are a few potential fixes that I could implement off the top of my head:

1. Set up another option called `ignoreRequestErrors` that defaults to `true`. If you set this to `false` then it will call `next(error)` when there is a problem with the request.
2. Add a property to the request object called `error` (maybe?) that contains the error details.

Option 1 seems to be more in line with keeping with common patterns. What are your thoughts? Do you have any other ideas for how this might be fixed?

Thanks for the issue.

**Comment by freerider7777** [comment]
> What isn't helpful here is that you can't easily see what the client error was.
Yep :)
I think both options would be useful and rather easy to implement.
For me option 2 seems also useful - we can handle the results of validation and decide what to do next - based on application settings ("write warning with error details and continue" in development mode or "answer with error" in production mode for example in single "next" middleware).

**Comment by Gi60s** [comment]
I like the idea of adding both. I'm not sure if I'll be able to get to this today, but I should be able to by tomorrow. I'll let you know when I've made the update.

**Comment by freerider7777** [comment]
Thanks! No need to hurry :)

**Comment by Gi60s** [comment]
I've made the changes and published to NPM, but I have not yet updated the docs.

There is an option now called `ignoreRequestErrors` that defaults to `true`. If there is a problem with the request then a property named `clientError` gets added to the request object.

Thanks for the issue and the patience.
